PP_5/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PP_5.DAL;
using PP_5.Models;

namespace PP_5.Controllers
{
    public class OrderController : Controller
    {
        private ShopContext db = new ShopContext();

        // GET: Order
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Customer);
            return View(orders.ToList());
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FIO");
            return View();
        }

        // POST: Order/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,Date,Status,Product_Count,CustomerID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FIO", order.CustomerID);
            return View(order);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FIO", order.CustomerID);
            return View(order);
        }

        // POST: Order/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,Date,Status,Product_Count,CustomerID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FIO", order.CustomerID);
            return View(order);
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PP_5/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PP_5.DAL;
using PP_5.Models;

namespace PP_5.Controllers
{
    public class ProductController : Controller
    {
        private ShopContext db = new ShopContext();

        // GET: Product
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Provider);
            return View(products.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.ProviderID = new SelectList(db.Providers, "ProviderID", "Name");
            return View();
        }

        // POST: Product/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,Name,Count,Warranty_Period,ProviderID,Component_TypeID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProviderID = new SelectList(db.Providers, "ProviderID", "Name", product.ProviderID);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProviderID = new SelectList(db.Providers, "ProviderID", "Name", product.ProviderID);
            return View(product);
        }

        // POST: Product/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,Name,Count,Warranty_Period,ProviderID,Component_TypeID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProviderID = new SelectList(db.Providers, "ProviderID", "Name", product.ProviderID);
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PP_5/Controllers/SignInController.cs
using PP_5.DAL;
using PP_5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace PP_5.Controllers
{
    public class SignInController : Controller
    {
        private ShopContext db = new ShopContext();
        // GET: SignIn
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(Customer customer)
        {
            if (ModelState.IsValid)
            {
                Customer existingCustomer = new Customer();
                try
                {
                    customer.Password = GetHashString(customer.Password);
                    existingCustomer = db.Customers.FirstOrDefault(c => c.Email == customer.Email && c.Password == customer.Password);
                }
                catch ( ArgumentNullException ex )
                {
                    ModelState.AddModelError("", $"Пользователь не найден: {ex.Message}");
                }
                if (existingCustomer.Password != null || existingCustomer.Email != null || existingCustomer != null)
                {
                    Session["CurrentCustomer"] = existingCustomer;
                    if (existingCustomer.root == UserRole.ADMIN)
                    {
                        return RedirectToAction("AdminProfile", "Profile");
                    }
                    else
                    {
                        return RedirectToAction("Profile", "Profile");
                    }
                }
                ModelState.AddModelError("", "Ошибка ввода логина или пароля");
            }
            return View(customer);
        }
        public static string GetHashString(string s)
        {
            byte[] bytes = Encoding.Unicode.GetBytes(s);
            MD5CryptoServiceProvider CSP = new MD5CryptoServiceProvider();
            byte[] byteHash = CSP.ComputeHash(bytes);
            string hash = "";
            foreach (byte b in byteHash)
            {
                hash += string.Format("{0:x2}", b);
            }
            return hash;
        }
    }
}

PP_5/Controllers/SignUpController.cs
using PP_5.DAL;
using PP_5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using System.Web.Helpers;
using System.Security.Policy;

namespace PP_5.Controllers
{
    public class SignUpController : Controller
    {
        private ShopContext _shopContext = new ShopContext();
        // GET: SignUp

        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(Customer customer)
        {
            if (ModelState.IsValid)
            {
                string emailPattern = @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$";
                string phonePattern = @"^(\+?\d{1,3}[-.\s]?(\(?\d{1,4}\)?)?[-.\s]?)?(\d{1,4}[-.\s]?){1,3}\d{1,4}$";
                if (!_shopContext.Customers.Any(y => y.Phone == customer.Phone) && !_shopContext.Customers.Any(z => z.Email == customer.Email))
                {
                    if(!string.IsNullOrEmpty(customer.Email) && !string.IsNullOrEmpty(customer.Phone)) 
                    {
                        if (Regex.IsMatch(customer.Email, emailPattern) && Regex.IsMatch(customer.Phone, phonePattern))
                        {
                            customer.Password = SignInController.GetHashString(customer.Password);
                            _shopContext.Customers.Add(customer);
                            _shopContext.SaveChanges();
                            return RedirectToAction("SignIn", "SignIn");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Почта или телефон не подходит");
                            return View(customer);
                        }
                    }
                    ModelState.AddModelError("", "Заполните все данные");
                    return View(customer);
                }
                ModelState.AddModelError("", "Пользователь с такими данными уже существует.");
            }
            return View(customer);
        }
    }
}

PP_5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DNS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/index.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("DNS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                </ul>
            </div>
            @Html.ActionLink("Sign In", "SignIn", "SignIn", new { area = "" }, new { @class = "btn btn-outline-light" })
            @Html.ActionLink("Sign Up", "SignUp", "SignUp", new { area = "" }, new { @class = "sign-button btn btn-outline-light" })
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="custom-footer bg-dark">
        <p>&copy; @DateTime.Now.Year - DNS - интернет магазин</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PP_5/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DNS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/index.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("DNS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Providers", "Index", "Provider", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Component_Types", "Index", "Component_Type", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Orders", "Index", "Order", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
            @Html.ActionLink("Profile", "AdminProfile", "ToolsUser", new { area = "" }, new { @class = "btn btn-outline-light" })
            @Html.ActionLink("Log Out", "LogOut", "ToolsUser", new { area = "" }, new { @class = "sign-button btn btn-outline-light" })
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="custom-footer bg-dark">
        <p>&copy; @DateTime.Now.Year - DNS - интернет магазин</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PP_5/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DNS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/index.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("DNS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Products", "Products", "ToolsUser", new { area = "" }, new { @class = "sign-button btn btn-outline-light" })</li>
                    <li>@Html.ActionLink("Orders", "Orders", "ToolsUser", new { area = "" }, new { @class = "sign-button btn btn-outline-light" })</li>
                </ul>
            </div>
            @Html.ActionLink("Profile", "Profile", "ToolsUser", new { area = "" }, new { @class = "btn btn-outline-light" })
            @Html.ActionLink("Log Out", "LogOut", "ToolsUser", new { area = "" }, new { @class = "sign-button btn btn-outline-light" })
        </div>
</nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="custom-footer bg-dark">
        <p>&copy; @DateTime.Now.Year - DNS - интернет магазин</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>